#
# Azure Pipelines configuration for building and testing urllib3 on Linux, Windows, and macOS.
#

trigger:
- master

jobs:
- job: LinuxMac
  strategy:
    matrix:
      MacPython27:
        VM_IMAGE: 'macOS-10.13'
        PYTHON_VERSION: '2.7'
        TOXENV: 'py27'
      MacPython34:
        VM_IMAGE: 'macOS-10.13'
        PYTHON_VERSION: '3.4'
        TOXENV: 'py34'
      MacPython35:
        VM_IMAGE: 'macOS-10.13'
        PYTHON_VERSION: '3.5'
        TOXENV: 'py35'
      MacPython36:
        VM_IMAGE: 'macOS-10.13'
        PYTHON_VERSION: '3.6'
        TOXENV: 'py36'
      MacPython37:
        VM_IMAGE: 'macOS-10.13'
        PYTHON_VERSION: '3.7'
        TOXENV: 'py37'
      LinuxPython27:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '2.7'
        TOXENV: 'py27'
      LinuxPython27-nobrotli:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '2.7'
        TOXENV: 'py27-nobrotli'
      LinuxPython27-flake8-py3:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '2.7'
        TOXENV: 'flake8-py3'
      LinuxPython27-gae:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '2.7'
        TOXENV: 'gae'
      LinuxPython27-docs:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '2.7'
        TOXENV: 'docs'            
      LinuxPython34:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '3.4'
        TOXENV: 'py34'
      LinuxPython35:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '3.5'
        TOXENV: 'py35'
      LinuxPython36:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '3.6'
        TOXENV: 'py36'
      LinuxPython37:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '3.7'
        TOXENV: 'py37'      
      LinuxPython37-nobrotli:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '3.7'
        TOXENV: 'py37-nobrotli'
      LinuxPython38:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '3.8'
        TOXENV: 'py38'
      LinuxPyPy54:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: 'pypy-5.4'
        TOXENV: 'pypy'         
  pool:
    vmImage: $(VM_IMAGE)     
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
        architecture: 'x64'
      displayName: 'Install Python'
    - script: env
      displayName: 'env'
    - script: openssl version
      displayName: 'openssl version'
    - script: python -c "import ssl; print(ssl.OPENSSL_VERSION)"
      displayName: 'import ssl'
    - script: ./_travis/install.sh
      displayName: 'install'
    - script: ./_travis/run.sh
      displayName: 'run'
    - script: ./_travis/upload_coverage.sh
      displayName: 'upload coverage -- need condition if succeed'
  # TODO: integration; deploy

- job: Windows
  strategy:
    matrix:
      WindowsPython27:
        VM_IMAGE: 'vs2017-win2016'
        PYTHON_VERSION: '2.7'
        TOXENV: 'py27'
      WindowsPython27-nobrotli:
        VM_IMAGE: 'vs2017-win2016'
        PYTHON_VERSION: '2.7'
        TOXENV: 'py27-nobrotli'       
      WindowsPython34:
        VM_IMAGE: 'vs2017-win2016'
        PYTHON_VERSION: '3.4'
        TOXENV: 'py34'
      WindowsPython35:
        VM_IMAGE: 'vs2017-win2016'
        PYTHON_VERSION: '3.5'
        TOXENV: 'py35'
      WindowsPython36:
        VM_IMAGE: 'vs2017-win2016'
        PYTHON_VERSION: '3.6'
        TOXENV: 'py36'
      WindowsPython37:
        VM_IMAGE: 'vs2017-win2016'
        PYTHON_VERSION: '3.7'
        TOXENV: 'py37'
      WindowsPython37-nobrotli:
        VM_IMAGE: 'vs2017-win2016'
        PYTHON_VERSION: '3.7'
        TOXENV: 'py37-nobrotli'                                                
  pool:
    vmImage: $(VM_IMAGE)     
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
        architecture: 'x64'
      displayName: 'Install Python'
    - script: pip install tox virtualenv
      displayName: 'Install tox'
    - script: tox
      displayName: 'test: tox'
    # TODO: activate.bat; codecov

- job: NotInstalled1
  strategy:
    matrix:
      LinuxPython38:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: '3.8'
        TOXENV: 'py38'    
  pool:
    vmImage: $(VM_IMAGE)     
  steps:
    - script: |
        sudo apt-get install -y git
        sudo apt-get install -y build-essential libbz2-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev tk-dev
    - script: |
        curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
    - script: |
        export PATH="~/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
    - script: pyenv install 3.8
    - script: env
      displayName: 'env'
    - script: openssl version
      displayName: 'openssl version'
    - script: python -c "import ssl; print(ssl.OPENSSL_VERSION)"
      displayName: 'import ssl'
    - script: ./_travis/install.sh
      displayName: 'install'
    - script: ./_travis/run.sh
      displayName: 'run'
    - script: ./_travis/upload_coverage.sh
      displayName: 'upload coverage -- need condition if succeed'
  # TODO: integration; deploy

- job: NotInstalled2
  strategy:
    matrix:
      LinuxPyPy54:
        VM_IMAGE: 'ubuntu-16.04'
        PYTHON_VERSION: 'pypy-5.4'
        TOXENV: 'pypy'         
  pool:
    vmImage: $(VM_IMAGE)     
  steps:
    - script: |
        sudo add-apt-repository ppa:pypy/ppa
        sudo apt-get update
        sudo apt-get install pypy pypy-dev pypy-tk
    - script: |
        wget -O - https://bootstrap.pypa.io/get-pip.py | sudo -H pypy -
        sudo cp /usr/bin/{pip,pipy}
        sudo sed -i -e "s/python/pypy/" -e "s/==/>=/g" /usr/bin/pipy
    - script: env
      displayName: 'env'
    - script: openssl version
      displayName: 'openssl version'
    - script: python -c "import ssl; print(ssl.OPENSSL_VERSION)"
      displayName: 'import ssl'
    - script: ./_travis/install.sh
      displayName: 'install'
    - script: ./_travis/run.sh
      displayName: 'run'
    - script: ./_travis/upload_coverage.sh
      displayName: 'upload coverage -- need condition if succeed'
  # TODO: integration; deploy

variables:
  GAE_SDK_PATH: $(Build.SourcesDirectory)/.cache/google_appengine
  PYTHONWARNINGS: always::DeprecationWarning
  PYPI_USERNAME: urllib3
# PYPI_PASSWORD is set in Travis control panel.